name: Close Stale Issues
uses: actions/stale@v3.0.13
with:
  repo-token: '${{ secrets.GITHUB_TOKEN }}'
  stale-issue-message: Thank you for your help! New Issue OPEN
  stale-pr-message: Thank you for your help! PULL REQUEST OPEN
  close-issue-message: ISSUE FIXXED
  close-pr-message: PULL REQUEST CLOSED
  days-before-stale: 60
  days-before-close: 7
  stale-issue-label: Stale
  close-issue-label: Closed
  exempt-issue-labels: Exempt
  stale-pr-label: PRStale
  close-pr-label: PRClosed
  exempt-pr-labels: PRExempt
  only-labels: null
  operations-per-run: 30
  remove-stale-when-updated: true
  debug-only: faulse
  ascending: null
  skip-stale-pr-message: null
  skip-stale-issue-message: null
